name: Java Integration Tests Maven 3.3.9

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests Maven 3.3.9

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: zulu
      - name: Load Maven 3.3.9
        run: ./mvnw -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=3.3.9 --no-transfer-progress
      - name: Build Setup
        run: ./mvnw -B -V clean install -Dlicense.skip=true -Dmaven.min-version=3.3.9
      - name: Integration Test with Maven
        run: ./mvnw -B -V -DtestSrc=remote -Prun-its clean install -Dinvoker.parallelThreads=4 -Dlicense.skip=true -Dmaven.min-version=3.3.9
